channels:
- https://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- python=3.6
- astropy
- matplotlib
- numpy
- photutils
- pysiaf
- pip
- pip:
    - jwcf
    - pystrometry
    - git+https://github.com/tonysohn/pystortion
    - git+https://github.com/spacetelescope/jwst
