channels:
- https://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- python=3.8
- astropy
- matplotlib
- numpy
- pandas
- photutils
- pip
- pip:
    - ipython
    - pysiaf
    - jwst
    - git+https://github.com/tonysohn/uhelpers
    - git+https://github.com/tonysohn/pystortion
    - git+https://github.com/spacetelescope/jwst-calibration-field
